name: Code Scan

on:
  push:

jobs:
  code-scan:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Setup Ruby
    #   uses: actions/setup-ruby@v1
    #   with:
    #     ruby-version: '2.7'
    # - name: Setup Brakeman
    #   run: |
    #     gem install bundler
    #     cd brakeman && bundle install
    # - name: Scan
    #   continue-on-error: true
    #   run: |
    #     brakeman/bin/brakeman -o output.sarif .
    # - name: Expose artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: SARIF report
    #     path: output.sarif
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: output.sarif.json
